server:
  port: 9296

spring:
  application:
    name: HMS-CONFIG-SERVER
  cloud:
    config:
      server:
        #bootstrap: true
        git:
          uri: https://github.com/IKCONDev/hms-config-server
          clone-on-start: true
